---
# tasks file for squid_proxy

- name: install squid3
  command: sudo apt-get -y install squid3

- name: create squid3 directory
  command: sudo mkdir /etc/squid3

- name: make squid3 writable
  command: sudo chown -R ubuntu:ubuntu /etc/squid3/

- name: copy template
  template:
    src: squid.conf.j2
    dest: "{{ squid3_conf }}"
    owner: ubuntu
    group: ubuntu
    mode: 0644
  notify: restart squid3
