---
# tasks file for aws_ec2

- name: gather facts about Ubuntu 17.04 AMIs published by Canonical (099720109477)
  ec2_ami_facts:
    owners: 099720109477
    filters:
      name: "ubuntu/images/ubuntu-zesty-17.04-*"
  register: ec2_ami_id

- name: gather VPC subnets
  ec2_vpc_subnet_facts:
  register: ec2_vpc_subnets

- name: create a new ec2 key pair, returns generated private key
  ec2_key:
    name: my_keypair
  register: ec2_private_ssh_key

- name: example using security group rule descriptions
  ec2_group:
    name: "{{ name }}"
    description: sg with rule descriptions
    vpc_id: vpc-xxxxxxxx
    profile: "{{ aws_profile }}"
    region: us-east-1
    rules:
      - proto: tcp
        ports:
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22

- name: Launch EC2 instance
  ec2:
    key_name: mykey
    instance_type: t2.micro
    image: ami-123456
    wait: yes
    group: webserver
    count: 1
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
